name: Run tests
on: [push, pull_request]

jobs:
  prepare_dependencies:
    name: Prepare dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            **/node_modules 
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline && yarn add @vue/cli -W
        
  lint:
    name: Lint
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            **/node_modules 
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter and unit tests
        run: |
          NODE_ENV=development yarn install --frozen-lockfile --prefer-offline
          cd packages/vue && yarn lint && yarn test:unit

  cypress-run: 
    name: e2e tests
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:      

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            **/node_modules 
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2        
        with:
          install: | 
            NODE_ENV=development yarn install --frozen-lockfile --prefer-offline
            cd packages/vue && yarn build-storybook
          start: yarn storybook
          wait-on: 'http://localhost:6006/'
          wait-on-timeout: 120
          command: cd packages/vue && yarn test:e2e:headless
          config-file: cypress.json
          browser: chrome
          headless: true

  build:
    name: Build
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            **/node_modules 
            packages/vue/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          NODE_ENV=development yarn install --frozen-lockfile 
          cd packages/vue && yarn build
